// src/lib/services/menu-item-service.ts

import { api, normalizeApiResponse } from "@/lib/util/api-client";
import { logError } from "@/lib/util/logger";

export interface ItemVariant {
  name: string;
  price: number;
  _id?: string;
}

export interface ItemModifier {
  groupId: string;
  required?: boolean;
  min?: number;
  max?: number;
}

export interface TenantMenuItem {
  _id?: string;
  id?: string;
  name: string;
  slug?: string;
  categoryIds?: string[];
  imageUrl?: string;
  description?: string;
  variants?: ItemVariant[];
  modifiers?: ItemModifier[];
  isActive?: boolean;
  featured?: boolean;
  priority?: number;
  // Stock tracking fields
  trackStock?: boolean;
  stockQty?: number;
  minStockThreshold?: number;
}

export interface ApiListResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
}

const ITEMS_BASE = "/t/menu/items";

export const MenuItemService = {
  async listItems(params?: {
    q?: string;
    page?: number;
    limit?: number;
    categoryId?: string;
    status?: string;
    includeRecipeVariants?: boolean;
    includeCategoryAddOns?: boolean;
  }): Promise<ApiListResponse<TenantMenuItem[]>> {
    try {
      const q = params?.q ?? "";
      const page = params?.page ?? 1;
      const limit = params?.limit ?? 50;
      const categoryId = params?.categoryId ?? "";
      const status = params?.status ?? "";
      const includeRecipeVariants = params?.includeRecipeVariants ?? false;
      const includeCategoryAddOns = params?.includeCategoryAddOns ?? false;

      let path = `${ITEMS_BASE}?q=${encodeURIComponent(q)}&page=${page}&limit=${limit}`;
      if (categoryId) path += `&categoryId=${encodeURIComponent(categoryId)}`;
      if (status) path += `&status=${encodeURIComponent(status)}`;
      if (includeRecipeVariants) path += `&includeRecipeVariants=1`;
      if (includeCategoryAddOns) path += `&includeCategoryAddOns=1`;

      const response = await api.get(path);
      const normalized = normalizeApiResponse<TenantMenuItem[]>(response);

      // Handle different API response structures
      let items = normalized.data;
      if (response.items) {
        items = response.items;
      } else if (response.result) {
        items = response.result;
      }

      return {
        success: normalized.success,
        data: items,
        message: normalized.message,
      };
    } catch (error: any) {
      logError("Error listing menu items", error, {
        component: "MenuItemService",
        action: "listItems",
      });
      return {
        success: false,
        message: error.message || "Failed to list menu items",
      };
    }
  },

  async getItem(id: string, params?: {
    includeRecipeVariants?: boolean;
    includeCategoryAddOns?: boolean;
  }): Promise<ApiListResponse<TenantMenuItem>> {
    try {
      const includeRecipeVariants = params?.includeRecipeVariants ?? false;
      const includeCategoryAddOns = params?.includeCategoryAddOns ?? false;

      let path = `${ITEMS_BASE}/${id}`;
      const queryParams = [];
      if (includeRecipeVariants) queryParams.push(`includeRecipeVariants=1`);
      if (includeCategoryAddOns) queryParams.push(`includeCategoryAddOns=1`);
      if (queryParams.length > 0) path += `?${queryParams.join("&")}`;

      const response = await api.get(path);
      const normalized = normalizeApiResponse<TenantMenuItem>(response);

      return {
        success: normalized.success,
        data: normalized.data,
        message: normalized.message,
      };
    } catch (error: any) {
      logError("Error getting menu item", error, {
        component: "MenuItemService",
        action: "getItem",
        itemId: id,
      });
      return {
        success: false,
        message: error.message || "Failed to get menu item",
      };
    }
  },

  async createItem(payload: Partial<TenantMenuItem>): Promise<ApiListResponse<TenantMenuItem>> {
    try {
      // Slug is auto-generated by backend - don't send it
      const apiPayload = {
        name: payload.name,
        categoryIds: payload.categoryIds ?? [],
        imageUrl: payload.imageUrl ?? "",
        description: payload.description ?? "",
        variants: payload.variants ?? [],
        modifiers: payload.modifiers ?? [],
        isActive: payload.isActive ?? true,
        featured: payload.featured ?? false,
        priority: payload.priority ?? 0,
        trackStock: payload.trackStock ?? false,
        stockQty: payload.stockQty ?? 0,
        minStockThreshold: payload.minStockThreshold ?? 0,
      };

      const response = await api.post(ITEMS_BASE, apiPayload);
      const normalized = normalizeApiResponse<TenantMenuItem>(response);

      return {
        success: normalized.success,
        data: normalized.data,
        message: normalized.message || "Menu item created successfully",
      };
    } catch (error: any) {
      logError("Error creating menu item", error, {
        component: "MenuItemService",
        action: "createItem",
      });
      return {
        success: false,
        message: error.message || "Failed to create menu item",
      };
    }
  },

  async updateItem(id: string, payload: Partial<TenantMenuItem>): Promise<ApiListResponse<TenantMenuItem>> {
    try {
      // Only include fields being updated
      // Slug is auto-generated by backend - don't send it
      const apiPayload: any = {};
      if (payload.name !== undefined) apiPayload.name = payload.name;
      if (payload.categoryIds !== undefined) apiPayload.categoryIds = payload.categoryIds;
      if (payload.imageUrl !== undefined) apiPayload.imageUrl = payload.imageUrl;
      if (payload.description !== undefined) apiPayload.description = payload.description;
      if (payload.variants !== undefined) apiPayload.variants = payload.variants;
      if (payload.modifiers !== undefined) apiPayload.modifiers = payload.modifiers;
      if (payload.isActive !== undefined) apiPayload.isActive = payload.isActive;
      if (payload.featured !== undefined) apiPayload.featured = payload.featured;
      if (payload.priority !== undefined) apiPayload.priority = payload.priority;
      if (payload.trackStock !== undefined) apiPayload.trackStock = payload.trackStock;
      if (payload.stockQty !== undefined) apiPayload.stockQty = payload.stockQty;
      if (payload.minStockThreshold !== undefined) apiPayload.minStockThreshold = payload.minStockThreshold;

      const response = await api.put(`${ITEMS_BASE}/${id}`, apiPayload);
      const normalized = normalizeApiResponse<TenantMenuItem>(response);

      return {
        success: normalized.success,
        data: normalized.data,
        message: normalized.message || "Menu item updated successfully",
      };
    } catch (error: any) {
      logError("Error updating menu item", error, {
        component: "MenuItemService",
        action: "updateItem",
        itemId: id,
      });
      return {
        success: false,
        message: error.message || "Failed to update menu item",
      };
    }
  },

  async deleteItem(id: string): Promise<ApiListResponse<null>> {
    try {
      const response = await api.delete(`${ITEMS_BASE}/${id}`);
      const normalized = normalizeApiResponse(response);

      return {
        success: normalized.success,
        message: normalized.message || "Menu item deleted successfully",
        data: null,
      };
    } catch (error: any) {
      logError("Error deleting menu item", error, {
        component: "MenuItemService",
        action: "deleteItem",
        itemId: id,
      });
      return {
        success: false,
        message: error.message || "Failed to delete menu item",
      };
    }
  },
};
