// src/lib/services/modifier-service.ts

import { buildHeaders } from "@/lib/util/service-helpers";

export interface ModifierOption {
  name: string;
  price?: number;
}

export interface TenantModifier {
  _id?: string;
  id?: string;
  name: string;
  key?: string; // slug/key
  selection?: "single" | "multiple";
  min?: number;
  max?: number;
  options?: ModifierOption[];
  isActive?: boolean;
}

export interface ApiListResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
}

const REMOTE_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || process.env.NEXT_PUBLIC_API_BASE || "https://api.tritechtechnologyllc.com";
const USE_PROXY = (process.env.NEXT_PUBLIC_USE_API_PROXY || "true").toLowerCase() === "true";
const MODIFIERS_BASE = "/t/menu/addons";

function buildUrl(path: string) {
  return USE_PROXY ? `/api${path}` : `${REMOTE_BASE}${path}`;
}

export const ModifierService = {
  async listModifiers(params?: { q?: string; page?: number; limit?: number }): Promise<ApiListResponse<TenantModifier[]>> {
    const q = params?.q ?? "";
    const page = params?.page ?? 1;
    const limit = params?.limit ?? 50;
    const url = buildUrl(`${MODIFIERS_BASE}?q=${encodeURIComponent(q)}&page=${page}&limit=${limit}`);
    const res = await fetch(url, { headers: buildHeaders() });
    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      return { success: false, message: data?.message || `List modifiers failed (${res.status})` };
    }

    // Backend returns: { status, message, items: [...], count, page, limit }
    const items: TenantModifier[] = data?.items ?? data?.result ?? [];
    return { success: true, data: items };
  },

  async getModifier(id: string): Promise<ApiListResponse<TenantModifier>> {
    const url = buildUrl(`${MODIFIERS_BASE}/${id}`);
    const res = await fetch(url, { headers: buildHeaders() });
    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      return { success: false, message: data?.message || `Get modifier failed (${res.status})` };
    }

    const modifier: TenantModifier = data?.result ?? data;
    return { success: true, data: modifier };
  },

  async createModifier(payload: Partial<TenantModifier>): Promise<ApiListResponse<TenantModifier>> {
    const url = buildUrl(`${MODIFIERS_BASE}`);

    // Key/slug is auto-generated by backend - don't send it
    // Map to API format
    const apiPayload = {
      name: payload.name,
      selection: payload.selection ?? "single",
      min: payload.min ?? 0,
      max: payload.max ?? 1,
      options: payload.options ?? [],
    };

    const res = await fetch(url, {
      method: "POST",
      headers: buildHeaders(),
      body: JSON.stringify(apiPayload),
    });
    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      return { success: false, message: data?.message || `Create modifier failed (${res.status})` };
    }

    const modifier: TenantModifier = data?.result ?? data;
    return { success: true, data: modifier };
  },

  async updateModifier(id: string, payload: Partial<TenantModifier>): Promise<ApiListResponse<TenantModifier>> {
    const url = buildUrl(`${MODIFIERS_BASE}/${id}`);

    // Only include fields being updated
    // Key/slug is auto-generated by backend - don't send it
    const apiPayload: any = {};
    if (payload.name !== undefined) apiPayload.name = payload.name;
    if (payload.selection !== undefined) apiPayload.selection = payload.selection;
    if (payload.min !== undefined) apiPayload.min = payload.min;
    if (payload.max !== undefined) apiPayload.max = payload.max;
    if (payload.options !== undefined) apiPayload.options = payload.options;

    const res = await fetch(url, {
      method: "PUT",
      headers: buildHeaders(),
      body: JSON.stringify(apiPayload),
    });
    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      return { success: false, message: data?.message || `Update modifier failed (${res.status})` };
    }

    const modifier: TenantModifier = data?.result ?? data;
    return { success: true, data: modifier };
  },

  async deleteModifier(id: string): Promise<ApiListResponse<null>> {
    const url = buildUrl(`${MODIFIERS_BASE}/${id}`);
    const res = await fetch(url, { method: "DELETE", headers: buildHeaders() });

    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      return { success: false, message: data?.message || `Delete modifier failed (${res.status})` };
    }

    return { success: true, data: null };
  },
};
