// src/lib/services/modifier-service.ts

import { api, normalizeApiResponse } from "@/lib/util/api-client";

export interface ModifierOption {
  name: string;
  price?: number;
}

export interface TenantModifier {
  _id?: string;
  id?: string;
  name: string;
  key?: string; // slug/key
  selection?: "single" | "multiple";
  min?: number;
  max?: number;
  options?: ModifierOption[];
  isActive?: boolean;
}

export interface ApiListResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
}

const MODIFIERS_BASE = "/t/menu/addons";

export const ModifierService = {
  async listModifiers(params?: { q?: string; page?: number; limit?: number }): Promise<ApiListResponse<TenantModifier[]>> {
    try {
      const q = params?.q ?? "";
      const page = params?.page ?? 1;
      const limit = params?.limit ?? 50;
      const path = `${MODIFIERS_BASE}?q=${encodeURIComponent(q)}&page=${page}&limit=${limit}`;

      const response = await api.get(path);
      const normalized = normalizeApiResponse<TenantModifier[]>(response);

      // Handle different API response structures
      let items = normalized.data;
      if (response.items) {
        items = response.items;
      } else if (response.result) {
        items = response.result;
      }

      return {
        success: normalized.success,
        data: items,
        message: normalized.message,
      };
    } catch (error: any) {
      console.error("Error listing modifiers:", error);
      return {
        success: false,
        message: error.message || "Failed to list modifiers",
      };
    }
  },

  async getModifier(id: string): Promise<ApiListResponse<TenantModifier>> {
    try {
      const response = await api.get(`${MODIFIERS_BASE}/${id}`);
      const normalized = normalizeApiResponse<TenantModifier>(response);

      return {
        success: normalized.success,
        data: normalized.data,
        message: normalized.message,
      };
    } catch (error: any) {
      console.error("Error getting modifier:", error);
      return {
        success: false,
        message: error.message || "Failed to get modifier",
      };
    }
  },

  async createModifier(payload: Partial<TenantModifier>): Promise<ApiListResponse<TenantModifier>> {
    try {
      // Key/slug is auto-generated by backend - don't send it
      const apiPayload = {
        name: payload.name,
        selection: payload.selection ?? "single",
        min: payload.min ?? 0,
        max: payload.max ?? 1,
        options: payload.options ?? [],
      };

      const response = await api.post(MODIFIERS_BASE, apiPayload);
      const normalized = normalizeApiResponse<TenantModifier>(response);

      return {
        success: normalized.success,
        data: normalized.data,
        message: normalized.message || "Modifier created successfully",
      };
    } catch (error: any) {
      console.error("Error creating modifier:", error);
      return {
        success: false,
        message: error.message || "Failed to create modifier",
      };
    }
  },

  async updateModifier(id: string, payload: Partial<TenantModifier>): Promise<ApiListResponse<TenantModifier>> {
    try {
      // Only include fields being updated
      // Key/slug is auto-generated by backend - don't send it
      const apiPayload: any = {};
      if (payload.name !== undefined) apiPayload.name = payload.name;
      if (payload.selection !== undefined) apiPayload.selection = payload.selection;
      if (payload.min !== undefined) apiPayload.min = payload.min;
      if (payload.max !== undefined) apiPayload.max = payload.max;
      if (payload.options !== undefined) apiPayload.options = payload.options;

      const response = await api.put(`${MODIFIERS_BASE}/${id}`, apiPayload);
      const normalized = normalizeApiResponse<TenantModifier>(response);

      return {
        success: normalized.success,
        data: normalized.data,
        message: normalized.message || "Modifier updated successfully",
      };
    } catch (error: any) {
      console.error("Error updating modifier:", error);
      return {
        success: false,
        message: error.message || "Failed to update modifier",
      };
    }
  },

  async deleteModifier(id: string): Promise<ApiListResponse<null>> {
    try {
      const response = await api.delete(`${MODIFIERS_BASE}/${id}`);
      const normalized = normalizeApiResponse(response);

      return {
        success: normalized.success,
        message: normalized.message || "Modifier deleted successfully",
        data: null,
      };
    } catch (error: any) {
      console.error("Error deleting modifier:", error);
      return {
        success: false,
        message: error.message || "Failed to delete modifier",
      };
    }
  },
};
