// types/menu.ts

// ===== MENU CATEGORY TYPES =====

export interface MenuCategory {
  _id?: string;
  name: string;
  slug: string;
  code: string;
  description?: string;
  parentId?: string | null;
  isActive: boolean;
  displayOrder: number;
  metadata?: Record<string, any>;
  createdAt?: string;
  updatedAt?: string;
}

export interface MenuCategoryPayload {
  name: string;
  slug: string;
  code: string;
  description?: string;
  parentId?: string | null;
  isActive?: boolean;
  displayOrder?: number;
  metadata?: Record<string, any>;
}

// ===== MENU ITEM TYPES =====

// Helper types for populated fields
export interface PopulatedRef {
  _id?: string;
  id?: string;
  name?: string;
  slug?: string;
}

// MenuItem matching Postman API - can have populated categoryId/recipeId or string IDs
export interface MenuItem {
  _id?: string;
  id?: string;
  name: string;
  slug?: string;
  code?: string;
  description?: string;
  categoryId: string | PopulatedRef; // Single category ID
  recipeId?: string | PopulatedRef;
  pricing: {
    basePrice: number;
    priceIncludesTax: boolean;
    currency: string;
  };
  isActive: boolean;
  displayOrder: number;
  tags?: string[];
  media?: MenuItemMedia[];
  branchIds?: string[];
  metadata?: Record<string, any>;
  createdAt?: string;
  updatedAt?: string;
}

export interface MenuItemMedia {
  url: string;
  alt?: string;
  type: string;
}

export interface MenuItemPayload {
  name: string;
  slug?: string; // Auto-generated by backend
  code?: string; // Auto-generated by backend
  description?: string;
  categoryId: string; // Single category ID
  recipeId?: string;
  pricing: {
    basePrice: number;
    priceIncludesTax?: boolean;
    currency?: string;
  };
  isActive?: boolean;
  displayOrder?: number;
  tags?: string[];
  media?: MenuItemMedia[];
  branchIds?: string[];
  metadata?: Record<string, any>;
}

// ===== MENU VARIATION TYPES =====

// Menu Variation - Links menu items to recipe variants with pricing
export interface MenuVariation {
  _id?: string;
  id?: string;
  menuItemId: string;
  recipeVariantId: string;
  name: string;
  type: "size" | "addon" | "custom";
  priceDelta: number; // Price difference from base menu item
  sizeMultiplier?: number;
  isDefault: boolean;
  isActive: boolean;
  displayOrder: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface MenuVariationPayload {
  menuItemId: string;
  recipeVariantId: string;
  name: string;
  type: "size" | "addon" | "custom";
  priceDelta: number;
  sizeMultiplier?: number;
  isDefault?: boolean;
  isActive?: boolean;
  displayOrder?: number;
}

// ===== API RESPONSE TYPES =====

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  error?: string;
}

export interface PaginatedResponse<T> {
  success: boolean;
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
  message?: string;
}

// ===== FILTER & UI STATE TYPES =====

export interface CategoryFilterOptions {
  searchTerm: string;
  statusFilter: "" | "active" | "inactive";
  parentFilter: string; // parent category ID
}

export interface MenuItemFilterOptions {
  searchTerm: string;
  statusFilter: "" | "active" | "inactive";
  categoryFilter: string; // category ID
}

export interface ModalState<T> {
  isOpen: boolean;
  editingItem: T | null;
}

export interface LoadingState {
  loading: boolean;
  actionLoading: boolean;
}

// ===== FORM VALIDATION TYPES =====

export interface ValidationError {
  field: string;
  message: string;
}

export interface FormValidationResult {
  isValid: boolean;
  errors: ValidationError[];
}

export interface ToastMessage {
  message: string;
  type: "success" | "error";
}

// ===== CONSTANTS =====

export const MENU_STATUS = ["active", "inactive"] as const;
export type MenuStatus = typeof MENU_STATUS[number];

export const CURRENCY_OPTIONS = ["SAR", "USD", "EUR", "GBP"] as const;
export type Currency = typeof CURRENCY_OPTIONS[number];

// ===== HELPER FUNCTIONS =====

/**
 * Extract string ID from either a string or populated reference object
 */
export function extractId(value: string | PopulatedRef | undefined | null): string {
  if (!value) return "";
  if (typeof value === "string") return value;
  return value._id || value.id || "";
}

// ===== DISPLAY/UI TYPES =====

export interface MenuCategoryOption {
  ID: string;
  Name: string;
  Code: string;
  Status: "Active" | "Inactive";
  Description: string;
  ParentCategory?: string;
  DisplayOrder: number;
  _raw?: MenuCategory; // Store raw data for editing
}

export interface MenuItemOption {
  ID: string;
  Name: string;
  Slug?: string;
  Code: string;
  Status: "Active" | "Inactive";
  Description: string;
  Category: string;
  CategoryId: string;
  Recipe?: string;
  RecipeId?: string;
  BasePrice: number;
  Currency: string;
  PriceIncludesTax: boolean;
  Tags: string[];
  DisplayOrder: number;
  ImageUrl?: string;
  _raw?: MenuItem; // Store raw data for editing
}
